// <auto-generated />
namespace ADIAss.core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ADIAssignmentv1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADIAssignmentv1));
        
        string IMigrationMetadata.Id
        {
            get { return "202011110640064_ADIAssignment-v1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
